apiVersion: v1
kind: Secret
metadata:
    name: my-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wkaTFPk=,iv:lW80Lt3RRj9+nSZMoYh4dHXuNCybhLlgHmytwJ93gaA=,tag:lu7k3tWbaBJXz37JBqlJ6A==,type:str]
    password: ENC[AES256_GCM,data:niCnpQXIsJwnttDLlTU=,iv:XIwl47GzOokURBOLSSQT9q064zpzW7i2z3F1FA+lTwo=,tag:l/F1l7RPp13fy3hK3MbiBg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:889546352481:key/f32b4229-e746-4a35-8bec-d6161f7194de
          created_at: "2025-05-29T07:37:20Z"
          enc: AQICAHizaqWPtOJ5pWAnyH1/tTm9t+fgCnJDb/vxsMITqC7FQQF2rql/v6pmjjowGC/K+syeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQME3txM2BABzcCFbu+AgEQgDt5MoSqafXLqeZOoOrkHJhENVBWHuLbHOuAov1NVskKV39PAclOcZvvxWTBGlcn43f6KC8S8e/2PFW31w==
          aws_profile: ""
    lastmodified: "2025-05-29T07:37:21Z"
    mac: ENC[AES256_GCM,data:jreTMV8k362OsPYMbybnn0Pr6xRCFf6oASsQpBZYvU7vtZKCqFSsJ0VM/hwmy7lUN0n+RxXPitIaf8GFzfOvdZO1oiSMf3cbLU4b4ncrvZT1IWoTCA84wRr9+zkTozmqxo0uvgSgXX1iM3jgOkcWzvH7uHAqQR096RLe3/9J6RQ=,iv:1pBbVH40yLepGVzRtf44ksZHCnbxTCxFpmSjNZFs5Nc=,tag:v3z1lN2JmnU3AotrVHJmYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
